<?php

class ToDoListTest extends \Tests\BaseKernelTestCase
{

    /**
     * @var \AppBundle\Service\ToDoListService $service
     */
    private $service;
    private $em;
    private $completedItem;
    private $incompletedItem;
    private $currentSemester;
    private $department;
    private $itemWithShortDeadline;
    private $itemWithAlmostShortDeadline;
    private $itemPastDeadline;
    private $itemMandatoryShortDeadline;
    private $itemMandatory;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $kernel = $this->createKernel();
        $kernel->boot();

        $service = $kernel->getContainer()->get('app.to_do_list_service');
        $this->service = $service;
        $em = $kernel->getContainer()->get('doctrine')->getManager();
        $this->em = $em;
        $toDoRepo = $em->getRepository('AppBundle:ToDoItem');
        $this->completedItem = $toDoRepo->findOneBy(['title' => 'completedToDoItem']);
        $this->incompletedItem = $toDoRepo->findOneBy(['title' => 'incompletedToDoItem']);
        $this->currentSemester = $em->getRepository('AppBundle:Semester')->findCurrentSemester();
        $this->department = $em->getRepository('AppBundle:Department')->findOneBy(['shortName' => 'NTNU']);

        $this->itemWithShortDeadline = $toDoRepo->findOneBy(['title' => 'shortDeadlineItem']);
        $this->itemWithAlmostShortDeadline = $toDoRepo->findOneBy(['title' => 'almostShortDeadlineItem']);
        $this->itemPastDeadline = $toDoRepo->findOneBy(['title' => 'pastDeadlineItem']);
        $this->itemMandatoryShortDeadline = $toDoRepo->findOneBy(['title' => 'mandatoryShortDeadlineItem']);
        $this->itemMandatory = $toDoRepo->findOneBy(['title' => 'mandatoryToDoItem']);


    }


    //testGetIncompleted?
    function testIsCompletedInSemesterByDepartment()
    {
        $todoItems = array($this->completedItem, $this->incompletedItem);
        $incompletedItems = $this->service->getIncompletedToDoItems($todoItems, $this->currentSemester, $this->department);
        $this->assertEquals(1, count($incompletedItems));
        $this->assertEquals($this->incompletedItem, $incompletedItems[0]);

    }

    function testGetToDoItemsWithShortDeadline()
    {
        $todoItems = array($this->itemWithShortDeadline, $this->incompletedItem, $this->itemWithAlmostShortDeadline, $this->itemPastDeadline);
        $shortDeadlines = $this->service->getToDoItemsWithShortDeadline($todoItems);
        $this->assertEquals(2, count($shortDeadlines));
        $this->assertContains($this->itemWithShortDeadline, $shortDeadlines);
        $this->assertContains($this->itemPastDeadline, $shortDeadlines);
    }


    function testGetMandatoryToDoItemsWithInsignificantDeadline()
    {
        $itemMandatoryShortDeadline = $this->itemMandatoryShortDeadline;
        $itemMandatoryNoShortDeadline = $this->itemMandatory;
        $itemShortDeadline = $this->itemWithShortDeadline;
        $itemNotMandatoryNoDeadline = $this->incompletedItem;
        $mandatoryResult = $this->service->getMandatoryToDoItemsWithInsignificantDeadline(
            array($itemMandatoryShortDeadline, $itemMandatoryNoShortDeadline, $itemShortDeadline, $itemNotMandatoryNoDeadline), $this->currentSemester);
        $this->assertEquals(1, count($mandatoryResult));
        $this->assertContains($itemMandatoryNoShortDeadline, $mandatoryResult);
        $nonMandatoryResult = $this->service->getNonMandatoryToDoItemsWithInsignificantDeadline(
            array($itemMandatoryShortDeadline, $itemMandatoryNoShortDeadline, $itemShortDeadline, $itemNotMandatoryNoDeadline),
            $this->currentSemester);
        $this->assertEquals(1, count($nonMandatoryResult));
        $this->assertContains($itemNotMandatoryNoDeadline, $nonMandatoryResult);

    }


}