language: php

php:
  - 7.0

before_script:
  - composer install

script:
  - ./bin/php-cs-fixer fix src/ --dry-run --diff -vv
  - ./bin/phpunit --configuration app/phpunit.xml.dist

notifications:
  slack: vektorweb:jYCfQkkXOJyzPZrxzQKIbTro
  email: false
