language: php

php:
  - 7.1

node_js:
  - 10

before_script:
  - composer install

script:
  - ./bin/php-cs-fixer fix src/ --dry-run --diff -vv
  - ./bin/phpunit --configuration app/phpunit.xml.dist

notifications:
  email: false
