language: php

php:
  - 7.4

node_js:
  - 14

before_script:
  - composer self-update --rollback
  - composer install

script:
  - ./bin/php-cs-fixer fix src/ --dry-run --diff -vv
  - ./bin/phpunit --configuration app/phpunit.xml.dist

notifications:
  email: false
