<?php

namespace AppBundle\Repository;

/**
 * ChangeLogItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeLogItemRepository extends \Doctrine\ORM\EntityRepository
{
}
