<?php

namespace AppBundle\Repository;

/**
 * ParentAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
