imports:
    - { resource: config_prod.yml }

parameters:
    google_api:
        client_id: '%google_api_client_id%'
        client_secret: '%google_api_client_secret%'
        refresh_token: '%google_api_refresh_token%'
        disabled: true

    slack.disable_delivery: false

swiftmailer:
    disable_delivery: true
