imports:
    - { resource: config_dev.yml }

parameters:
    slack.disable_delivery: true
    google_api:
        client_id: 'test_client_id'
        client_secret: 'test_client_secret'
        refresh_token: 'test_refresh_token'
        disabled: true

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/cache/test/test.db
                #memory: true
                charset: utf8
