client_home:
    path: /
    defaults: { _controller: AppBundle:FrontEnd:index }

client_assistants:
    path: /assistenter
    defaults: { _controller: AppBundle:FrontEnd:index }

client_team:
    path: /team
    defaults: { _controller: AppBundle:FrontEnd:index }

client_about:
    path: /om-oss
    defaults: { _controller: AppBundle:FrontEnd:index }

client_contact:
    path: /kontakt
    defaults: { _controller: AppBundle:FrontEnd:index }
