# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: "@AppBundle/Resources/config/forms.yml" }

services:
    AppBundle\DataFixtures\ORM\:
        resource: '../../src/AppBundle/DataFixtures/ORM'
        tags: ['doctrine.fixture.orm']

    app.twig_extension:
        class: AppBundle\Twig\Extension\StaticContentExtension
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: twig.extension }

    app.twig_sponsors_extension:
        class: AppBundle\Twig\Extension\SponsorsExtension
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: twig.extension }

    app.reversed_role_hierarchy:
        class: AppBundle\Role\ReversedRoleHierarchy
        arguments: ["%security.role_hierarchy.roles%"]

    app.content_mode:
        class: AppBundle\Service\ContentModeManager
        arguments: ['@session']

    app.admission_notifier:
        class: AppBundle\Service\AdmissionNotifier
        arguments: ['@doctrine.orm.default_entity_manager', '@app.email_sender', '@app.logger', '@validator', '%daily_admission_notifier_limit%']

    app.admission_statistics:
        class: AppBundle\Service\AdmissionStatistics

    app.application_manager:
        class: AppBundle\Service\ApplicationManager

    app.content_mode_twig_extension:
        class: AppBundle\Twig\Extension\ContentModeExtension
        arguments: ['@app.content_mode']
        tags:
            - { name: twig.extension }

    app.slug_maker:
        class: AppBundle\Service\SlugMaker
        arguments: ['@doctrine.orm.default_entity_manager']

    app.user_service:
        class: AppBundle\Service\UserService
        arguments: ['@security.token_storage']

    guzzle.slack:
        class: GuzzleHttp\Client
        arguments:
            - { timeout: 2 }

