# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\Extension\StaticContentExtension
        arguments:
              doctrine: "@doctrine.orm.default_entity_manager"
        tags:
            - { name: twig.extension }

    app.twig_sponsors_extension:
        class: AppBundle\Twig\Extension\SponsorsExtension
        arguments:
             doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    app.reversed_role_hierarchy:
        class: AppBundle\Role\ReversedRoleHierarchy
        arguments: ["%security.role_hierarchy.roles%"]

    app.content_mode:
        class: AppBundle\Service\ContentModeManager
        arguments: ['@session']

    app.admission_notifier:
        class: AppBundle\Service\AdmissionNotifier
        arguments: ['@doctrine.orm.default_entity_manager', '@app.email_sender', '@app.logger', '@validator', '%daily_admission_notifier_limit%']

    app.admission_statistics:
        class: AppBundle\Service\AdmissionStatistics

    app.application_manager:
        class: AppBundle\Service\ApplicationManager

    app.content_mode_twig_extension:
        class: AppBundle\Twig\Extension\ContentModeExtension
        arguments: ['@app.content_mode']
        tags:
            - { name: twig.extension }

    app.access_twig_extension:
        class: AppBundle\Twig\Extension\AccessExtension
        arguments: ['@app.access_control']
        tags:
            - { name: twig.extension }

    app.route_display_twig_extension:
        class: AppBundle\Twig\Extension\RouteDisplayExtension
        arguments: ['@router.default']
        tags:
            - { name: twig.extension }

    app.slug_maker:
        class: AppBundle\Service\SlugMaker
        arguments: ['@doctrine.orm.default_entity_manager']

    guzzle.slack:
        class: GuzzleHttp\Client
        arguments:
            - { timeout: 2 }

    app.access_control:
        class: AppBundle\Service\AccessControlService
        arguments: ['@doctrine.orm.default_entity_manager', '@router', '@app.roles', '@security.token_storage']

    app.access_control_subscriber:
        class: AppBundle\EventSubscriber\AccessControlSubscriber
        arguments: ['@app.access_control']
        tags:
            - { name: kernel.event_subscriber }

