# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\Extension\StaticContentExtension
        arguments:
              doctrine: "@doctrine.orm.default_entity_manager"
        tags:
            - { name: twig.extension }

    app.twig_sponsors_extension:
        class: AppBundle\Twig\Extension\SponsorsExtension
        arguments:
             doctrine: "@doctrine"
        tags:
            - { name: twig.extension }

    app.reversed_role_hierarchy:
        class: AppBundle\Role\ReversedRoleHierarchy
        arguments: ["%security.role_hierarchy.roles%"]

    app.content_mode:
        class: AppBundle\Service\ContentModeManager
        arguments: ['@session']

    app.admission_notifier:
        class: AppBundle\Service\AdmissionNotifier
        arguments: ['@doctrine.orm.default_entity_manager', '@app.email_sender', '@app.logger']

    app.content_mode_twig_extension:
        class: AppBundle\Twig\Extension\ContentModeExtension
        arguments: ['@app.content_mode']
        tags:
            - { name: twig.extension }

    guzzle.slack:
        class: GuzzleHttp\Client
        arguments:
            - { timeout: 2 }

