services:
    _defaults:
        autowire: true
        autoconfigure: true
        tags:
            - { name: twig.extension }

    AppBundle\Twig\Extension\:
        resource: "../../src/AppBundle/Twig/Extension"

    AppBundle\Twig\Extension\AssetExtension:
        arguments:
            $rootDir: '%kernel.project_dir%'
