<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Admission;
use AppBundle\Entity\Department;
use AppBundle\Entity\Semester;
use AppBundle\Entity\User;
use AppBundle\Repository\Contract\AdmissionRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * AdmissionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmissionRepository extends EntityRepository implements AdmissionRepositoryInterface
{
    /**
     * Finds all applications that have a conducted interview.
     *
     * @param Department|null $department
     * @param Semester|null $semester
     *
     * @return Admission[]
     */
    public function findInterviewedApplicants($department = null, $semester = null): array
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->join('a.statistic', 'stat')
            ->join('stat.semester', 'sem')
            ->join('sem.department', 'd')
            ->join('a.interview', 'i')
            ->where('i.interviewed = 1');

        if (null !== $department) {
            $qb->andWhere('d = :department')
                ->setParameter('department', $department);
        }

        if (null !== $semester) {
            $qb->andWhere('sem = :semester')
                ->setParameter('semester', $semester);
        }
        $qb->orderBy('a.userCreated', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Finds all applications that have a conducted interview.
     *
     * @param Department $department
     * @param Semester   $semester
     * @param User       $interviewer
     *
     * @return Admission[]
     */
    public function findInterviewedApplicantsByInterviewer($department, $semester, $interviewer): array
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->join('a.statistic', 'stat')
            ->join('stat.semester', 'sem')
            ->join('sem.department', 'd')
            ->join('a.interview', 'i')
            ->where('i.interviewed = 1')
            ->andWhere('i.interviewer = :interviewer')
            ->setParameter('interviewer', $interviewer);

        if (null !== $department) {
            $qb->andWhere('d = :department')
                ->setParameter('department', $department);
        }

        if (null !== $semester) {
            $qb->andWhere('sem = :semester')
                ->setParameter('semester', $semester);
        }
        $qb->orderBy('a.userCreated', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Finds all applications that have been assigned an interview that has not yet been conducted.
     *
     * @param Department|null $department
     * @param Semester|null $semester
     *
     * @return Admission[]
     */
    public function findAssignedApplicants($department = null, $semester = null): array
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->join('a.statistic', 'stat')
            ->join('stat.semester', 'sem')
            ->join('sem.department', 'd')
            ->join('a.interview', 'i')
            ->where('i.interviewed = 0');

        if (null !== $department) {
            $qb->andWhere('d = :department')
                ->setParameter('department', $department);
        }

        if (null !== $semester) {
            $qb->andWhere('sem = :semester')
                ->setParameter('semester', $semester);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * Finds all applications without an interview, or without a conducted interview.
     *
     * @param Department|null $department
     * @param Semester|null $semester
     *
     * @return Admission[]
     */
    public function findNewApplicants($department = null, $semester = null): array
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a')
            ->join('a.statistic', 'stat')
            ->join('stat.semester', 'sem')
            ->join('sem.department', 'd')
            ->leftJoin('a.interview', 'i')
            ->where('i.interviewed = 0')
            ->orWhere('i is NULL');

        if (null !== $department) {
            $qb->andWhere('d = :department')
                ->setParameter('department', $department);
        }

        if (null !== $semester) {
            $qb->andWhere('sem = :semester')
                ->setParameter('semester', $semester);
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param int $id
     * @return Admission
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findApplicantById($id): Admission
    {
        return $this->createQueryBuilder('Application')
            ->select('Application')
            ->where('Application.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * @param int $id
     * @return object ApplicationStatistic entity
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findApplicantStatisticById($id): object
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('ApplicationStatistic')
            ->where('ApplicationStatistic.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * @return int
     */
    public function numOfApplications(): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.id)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @return int
     */
    public function numOfSemesters(): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.semester)')
            ->distinct()
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param Semester $semester
     * @return int
     */
    public function numOfSemester($semester): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.semester)')
            ->where('ApplicationStatistic.semester = :semester')
            ->setParameter('semester', $semester)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $gender
     * @return int
     */
    public function numOfGender($gender): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.gender)')
            ->where('ApplicationStatistic.gender = :gender')
            ->setParameter('gender', $gender)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param bool $participated
     * @return int
     */
    public function numOfPreviousParticipation($participated): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.gender)')
            ->where('ApplicationStatistic.previousParticipation = :participated')
            ->setParameter('participated', $participated)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param bool $accepted
     * @return int
     */
    public function numOfAccepted($accepted): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.accepted)')
            ->where('ApplicationStatistic.accepted = :accepted')
            ->setParameter('accepted', $accepted)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $yearOfStudy
     * @return int
     */
    public function numOfYearOfStudy($yearOfStudy): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.yearOfStudy)')
            ->where('ApplicationStatistic.yearOfStudy = :yearOfStudy')
            ->setParameter('yearOfStudy', $yearOfStudy)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param string $fieldOfStudy
     * @return int
     */
    public function numOfFieldOfStudy($fieldOfStudy): int
    {
        return $this->createQueryBuilder('ApplicationStatistic')
            ->select('count(ApplicationStatistic.fieldOfStudy)')
            ->where('ApplicationStatistic.fieldOfStudy = :fieldOfStudy')
            ->setParameter('fieldOfStudy', $fieldOfStudy)
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param int $department
     * @return int
     */
    public function numOfDepartment($department): int
    {
        $numUsers = $this->getEntityManager()->createQuery('

		SELECT COUNT (AppS.id)
		FROM AppBundle:ApplicationStatistic AppS
		JOIN AppS.semester s
		JOIN s.department d
		WHERE d.id = :department

		')
            ->setParameter('department', $department)
            ->getSingleScalarResult();

        return $numUsers;
    }
}
