<?php

namespace AppBundle\Entity\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSortByNewest()
    {
        return $this->findBy(array(), array('created_at' => 'DESC'));
    }
}
