<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Repository\Contract\FeedbackRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository implements FeedbackRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function findAllSortByNewest(): array
    {
        return $this->findBy(array(), array('created_at' => 'DESC'));
    }
}
