<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\ImageGallery;
use Doctrine\ORM\EntityRepository;

/**
 * ImageGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGalleryRepository extends EntityRepository
{
}
