<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\ImageGallery;
use Doctrine\ORM\EntityRepository;

/**
 * ImageGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGalleryRepository extends EntityRepository
{
    /**
     * @param string $referenceName
     * @return ImageGallery
     */
    public function findByReferenceName($referenceName)
    {
        return $imageGallery = $this->createQueryBuilder('image_gallery')
            ->select('image_gallery')
            ->where('image_gallery.referenceName = :reference_name')
            ->setParameter('reference_name', $referenceName)
            ->getQuery()
            ->getSingleResult();
    }
}
