<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Interview;
use AppBundle\Entity\Semester;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * InterviewRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends EntityRepository
{
    public function findAllInterviewedInterviewsBySemester($semester)
    {
        $interviews = $this->getEntityManager()->createQuery('
		SELECT interview
		FROM AppBundle:Interview interview
		JOIN AppBundle:Application app
		WITH interview.application = app
		JOIN AppBundle:ApplicationStatistic appStat
		WITH app.statistic = appStat
		WHERE interview.interviewed = 1
		AND appStat.semester = :semester
		')
            ->setParameter('semester', $semester)
            ->getResult();

        return $interviews;
    }

    /**
     * @param User     $user
     * @param Semester $semester
     *
     * @return int
     */
    public function numberOfInterviewsByUserInSemester(User $user, Semester $semester)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT COUNT(i)
        FROM AppBundle:Interview i
        JOIN AppBundle:Application a
        WITH a.interview = i
        WHERE i.interviewer = ?1
        AND a.semester = ?2
        AND a.previousParticipation = 0
        ')
            ->setParameter(1, $user)
            ->setParameter(2, $semester);

        return $query->getSingleScalarResult();
    }

    public function findLatestInterviewByUser(User $user)
    {
        $query = $this->getEntityManager()->createQuery('
        SELECT i
        FROM AppBundle:Interview i
        WHERE i.user = ?1
        ORDER BY i.conducted ASC
        ')
            ->setParameter(1, $user)
            ->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    /**
     * @param string $responseCode
     *
     * @return Interview
     */
    public function findByResponseCode(string $responseCode)
    {
        return $this->createQueryBuilder('interview')
            ->where('interview.responseCode = :responseCode')
            ->setParameter('responseCode', $responseCode)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
