<?php
namespace AppBundle\Entity\Repository;
use AppBundle\Entity\Semester;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
/**
 * InterviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterviewRepository extends EntityRepository
{
    public function findAllInterviewedInterviewsBySemester($semester){
        $interviews =  $this->getEntityManager()->createQuery("
		SELECT interview
		FROM AppBundle:Interview interview
		JOIN AppBundle:Application app
		WITH interview.application = app
		JOIN AppBundle:ApplicationStatistic appStat
		WITH app.statistic = appStat
		WHERE interview.interviewed = 1
		AND appStat.semester = :semester
		")
            ->setParameter('semester', $semester)
            ->getResult();
        return $interviews;
    }

    /**
     * @param User $user
     * @param Semester $semester
     * @return integer
     */
    public function numberOfInterviewsByUserInSemester(User $user, Semester $semester){
        $query = $this->getEntityManager()->createQuery("
        SELECT COUNT(i)
        FROM AppBundle:Interview i
        JOIN AppBundle:Application a
        WITH a.interview = i
        WHERE i.interviewer = ?1
        AND a.semester = ?2
        ")
            ->setParameter(1, $user)
            ->setParameter(2, $semester);
        return $query->getSingleScalarResult();
    }
}