<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\PasswordReset;
use AppBundle\Entity\User;
use AppBundle\Repository\Contract\PasswordResetRepositoryInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * PasswordResetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasswordResetRepository extends EntityRepository implements PasswordResetRepositoryInterface
{
    /**
     * @param User $user
     * @return PasswordReset[]
     */
    public function findByUser(User $user): array
    {
        return $this->createQueryBuilder('password_reset')
            ->select('password_reset')
            ->where('password_reset.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
    /**
     * @param string $hashedResetCode
     * @return User
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function findUserByResetcode($hashedResetCode): User
    {
        return $this->createQueryBuilder('PasswordReset')
            ->select('PasswordReset.user')
            ->where('PasswordReset.hashedResetCode = :hashedResetCode')
            ->setParameter('hashedResetCode', $hashedResetCode)
            ->getQuery()
            ->getSingleResult();
    }

    /**
     * @param string $hashedResetCode
     *
     * @return PasswordReset|null
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     */
    public function findPasswordResetByHashedResetCode($hashedResetCode): ?PasswordReset
    {
        return $this->createQueryBuilder('PasswordReset')
            ->select('PasswordReset')
            ->where('PasswordReset.hashedResetCode = :hashedResetCode')
            ->setParameter('hashedResetCode', $hashedResetCode)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function deletePasswordResetByHashedResetCode($hashedResetCode)
    {
        return $this->createQueryBuilder('PasswordReset')
            ->delete()
            ->where('PasswordReset.hashedResetCode = :hashedResetCode')
            ->setParameter('hashedResetCode', $hashedResetCode)
            ->getQuery()
            ->getResult();
    }

    public function deletePasswordResetsByUser($user)
    {
        return $this->createQueryBuilder('PasswordReset')
            ->delete()
            ->where('PasswordReset.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
