<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * QuickLinkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuickLinkRepository extends EntityRepository
{
    public function findAllByOwner(User $owner)
    {
        return $this->createQueryBuilder('quickLink')
            ->select('quickLink')
            ->where('quickLink.owner = :owner')
            ->setParameter('owner', $owner)
            ->getQuery()
            ->getResult();
    }
}
