<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Signature;
use AppBundle\Entity\User;
use AppBundle\Repository\Contract\SignatureRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * SignatureRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignatureRepository extends EntityRepository implements SignatureRepositoryInterface
{
    /**
     * @param User $user
     *
     * @return Signature|null
     */
    public function findByUser(User $user): ?Signature
    {
        return $this->createQueryBuilder('signature')
            ->select('signature')
            ->where('signature.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
