<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\StaticContent;
use AppBundle\Repository\Contract\StaticContentRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * StaticContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticContentRepository extends EntityRepository implements StaticContentRepositoryInterface
{
    /**
     * @param string $htmlId
     *
     * @return StaticContent|null
     */
    public function findOneByHtmlId(string $htmlId): ?StaticContent
    {
        return $this->createQueryBuilder('sc')
            ->where('sc.htmlId = :htmlId')
            ->setParameter('htmlId', $htmlId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
