<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Semester;
use AppBundle\Entity\Substitute;
use Doctrine\ORM\EntityRepository;

/**
 * SubstituteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstituteRepository extends EntityRepository
{
    /**
     * @param Semester $semester
     *
     * @return Substitute[]
     */
    public function findSubstitutesBySemester(Semester $semester){
        return $this->createQueryBuilder('substitute')
            ->select('substitute')
            ->join('substitute.application', 'application')
            ->where('application.semester = :semester')
            ->setParameter('semester', $semester)
            ->getQuery()
            ->getResult();
    }
}