<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnhandAccessRuleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnhandledAccessRuleRepository extends EntityRepository
{
    public function findByResourceAndMethod(string $resource, string $method)
    {
        return $this->createQueryBuilder('rule')
            ->where('rule.resource = :resource')
            ->setParameter('resource', $resource)
            ->andWhere('rule.method = :method')
            ->setParameter('method', $method)
            ->getQuery()
            ->getResult();
    }
}
