<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\UnhandledAccessRule;
use AppBundle\Repository\Contract\UnhandledAccessRuleRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * UnhandAccessRuleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnhandledAccessRuleRepository extends EntityRepository implements UnhandledAccessRuleRepositoryInterface
{
    /**
     * @param string $resource
     * @param string $method
     * @return UnhandledAccessRule[]
     */
    public function findByResourceAndMethod(string $resource, string $method): array
    {
        return $this->createQueryBuilder('rule')
            ->where('rule.resource = :resource')
            ->setParameter('resource', $resource)
            ->andWhere('rule.method = :method')
            ->setParameter('method', $method)
            ->getQuery()
            ->getResult();
    }
}
