<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WorkHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkHistoryRepository extends EntityRepository {
	
	public function findActiveWorkHistories(){
		
		$today = new \DateTime('now');
		$workHistories =  $this->getEntityManager()->createQuery("
		SELECT whistory
		FROM AppBundle:WorkHistory whistory
		WHERE (whistory.startDate < :today
		AND whistory.endDate > :today)
		OR (whistory.startDate < :today
		AND whistory.endDate is NULL)
		")
		->setParameter('today', $today)
		->getResult();

		return $workHistories;
	}
	
	public function findActiveWorkHistoriesByUser($user){
		
		$today = new \DateTime('now');
		$workHistories =  $this->getEntityManager()->createQuery("
		SELECT whistory
		FROM AppBundle:WorkHistory whistory
		
		WHERE (whistory.startDate < :today
		AND whistory.endDate > :today
		AND whistory.user = :user)
		
		OR (whistory.startDate < :today
		AND whistory.endDate is NULL
		AND whistory.user = :user )
		
		")
		->setParameter('user', $user)
		->setParameter('today', $today)
		->getResult();

		return $workHistories;
	}
	
}
