sponsors:
    type: rest
    resource: "../src/App/Controller/Api/SponsorController.php"

departments:
    type: rest
    resource: "../src/App/Controller/Api/DepartmentController.php"

teams:
    type: rest
    resource: "../src/App/Controller/Api/TeamController.php"

applications:
    type: rest
    resource: "../src/App/Controller/Api/ApplicationController.php"

receipts:
    type: rest
    resource: "../src/App/Controller/Api/ReceiptController.php"

users:
    type: rest
    resource: "../src/App/Controller/Api/UserController.php"
