services:
    _defaults:
        autowire: true
        autoconfigure: true
        tags:
            - { name: validator.constraint_validator }

    App\Validator\Constraints\:
        resource: "../src/App/Validator/Constraints"
