services:
  app.sms:
    class: AppBundle\Sms\SmsSender
    arguments: ['%kernel.environment%', '@app.gateway_api_sms', '@app.slack_sms']

  app.gateway_api_sms:
    class: AppBundle\Sms\GatewayAPI
    arguments: ['%gateway_sms%', '@app.logger', '@app.slack_sms']

  app.slack_sms:
    class: AppBundle\Sms\SlackSms
    arguments: ['@app.slack_messenger']

  app.logger:
    class: AppBundle\Service\LogService
    arguments: ['@logger', '@app.slack_messenger', '@app.user_service', '@request_stack', '%kernel.environment%']

  app.mailer:
    class: AppBundle\Mailer\Mailer
    arguments: ['%kernel.environment%', '@app.google_gmail', '@mailer', '@app.slack_mailer']

  app.slack_mailer:
      class: AppBundle\Service\SlackMailer
      arguments: ['@app.slack_messenger']

  app.google_service:
      class: AppBundle\Google\GoogleService
      abstract: true
      arguments: ['%google_api%', '@app.logger']

  app.google_gmail:
      class: AppBundle\Google\Gmail
      parent: app.google_service
      calls:
        - [setDefaultEmail, ['%default_from_email%']]

  app.google_users:
      class: AppBundle\Google\GoogleUsers
      parent: app.google_service

  app.google_groups:
      class: AppBundle\Google\GoogleGroups
      parent: app.google_service

  app.google_drive:
      class: AppBundle\Google\GoogleDrive
      parent: app.google_service

  app.google_api:
      class: AppBundle\Google\GoogleAPI
      arguments: ['%google_api%', '@app.google_users', '@app.google_groups']

  app.geolocation:
      class: AppBundle\Service\GeoLocation
      arguments: ['%ipinfo_token%', '%geo_ignored_asns%', '@doctrine.orm.entity_manager', '@session', '@request_stack', '@app.logger']

  app.company_email_maker:
    class: AppBundle\Service\CompanyEmailMaker
    arguments: ['@doctrine.orm.default_entity_manager', '@app.logger']

  app.email_sender:
    class: AppBundle\Service\EmailSender
    arguments: ['@app.mailer', '@twig', '@router', '@app.logger', '%default_from_email%', '%economy_email%']

  app.slack_messenger:
    class: AppBundle\Service\SlackMessenger
    arguments: ['@nexy_slack.client', '%slack.notification_channel%', '%slack.log_channel%', '%slack.disable_delivery%', '@logger']

  app.user.registration:
    class: AppBundle\Service\UserRegistration
    arguments: ['@twig', '@doctrine.orm.default_entity_manager', '@app.mailer', '@app.logger']

  app.roles:
    class: AppBundle\Service\RoleManager
    arguments: ['@security.authorization_checker', '@doctrine.orm.entity_manager', '@app.logger', '@app.google_users']

  app.interview.manager:
    class: AppBundle\Service\InterviewManager
    arguments: ['@security.token_storage', '@security.authorization_checker', '@app.mailer', '@twig', '@app.logger', '@doctrine.orm.entity_manager', '@router', '@app.sms']

  app.password_manager:
      class: AppBundle\Service\PasswordManager
      arguments: ['@doctrine.orm.default_entity_manager', '@app.mailer', '@twig', '@app.logger']

  app.interview_notification_manager:
      class: AppBundle\Service\InterviewNotificationManager
      arguments: ['@app.slack_messenger', '@application.data', '@router']

  app.interview_counter:
    class: AppBundle\Service\InterviewCounter

  app.sbs_data:
    class: AppBundle\Service\SbsData
    parent: application.data

  app.safe_html_extension:
    class: AppBundle\Twig\Extension\SafeHtmlExtension
    public: false
    tags:
      - { name: twig.extension }

  app.sorter:
    class: AppBundle\Service\Sorter

  app.filter_service:
    class: AppBundle\Service\FilterService

  app.department_extension:
    class: AppBundle\Twig\Extension\DepartmentExtension
    arguments: ['@app.geolocation', '@doctrine.orm.default_entity_manager']
    tags:
      - { name: twig.extension }

  app.semester_extension:
    class: AppBundle\Twig\Extension\SemesterExtension
    arguments: ['@doctrine.orm.default_entity_manager']
    tags:
      - { name: twig.extension }

  app.role_extension:
    class: AppBundle\Twig\Extension\RoleExtension
    arguments: ['@security.authorization_checker', '@security.token_storage', '@app.roles']
    tags:
        - { name: twig.extension }

  app.exception_subscriber:
    class: AppBundle\EventSubscriber\ExceptionSubscriber
    arguments: ['@app.logger', '@logger']
    tags:
      - { name: kernel.event_subscriber }

  app.application_subscriber:
    class: AppBundle\EventSubscriber\ApplicationSubscriber
    arguments: ['@app.mailer', '@twig', '@app.logger', '@app.admission_notifier', '@app.user.registration']
    tags:
      - { name: kernel.event_subscriber }

  app.team_application_subscriber:
    class: AppBundle\EventSubscriber\TeamApplicationSubscriber
    arguments: ['@app.mailer', '@twig', '@session', '@app.logger', '@app.slack_messenger', '@router']
    tags:
      - { name: kernel.event_subscriber }

  app.team_interest_subscriber:
    class: AppBundle\EventSubscriber\TeamInterestSubscriber
    arguments: ['@app.mailer', '@twig','@session' ]
    tags:
      - { name: kernel.event_subscriber }

  app.assistant_history_subscriber:
    class: AppBundle\EventSubscriber\AssistantHistorySubscriber
    arguments: ['@session', '@logger', '@doctrine.orm.default_entity_manager', '@app.user.registration']
    tags:
      - { name: kernel.event_subscriber }

  app.interview_subscriber:
      class: AppBundle\EventSubscriber\InterviewSubscriber
      arguments: ['@app.mailer', '@twig', '@session', '@app.logger', '@app.sbs_data', '@app.interview_notification_manager', '@app.interview.manager', '@app.sms', '@router']
      tags:
        - { name: kernel.event_subscriber }

  app.support_ticket_subscriber:
      class: AppBundle\EventSubscriber\SupportTicketSubscriber
      arguments: ['@app.email_sender', '@app.slack_messenger', '@session', '@app.logger']
      tags:
        - { name: kernel.event_subscriber }

  app.team_membership_subscriber:
    class: AppBundle\EventSubscriber\TeamMembershipSubscriber
    arguments: ['@session', '@app.logger', '@app.roles']
    tags:
        - { name: kernel.event_subscriber }

  app.user_subscriber:
    class: AppBundle\EventSubscriber\UserSubscriber
    arguments: ['@app.logger']
    tags:
        - { name: kernel.event_subscriber }

  app.g_suite_subscriber:
    class: AppBundle\EventSubscriber\GSuiteSubscriber
    arguments: ['@app.logger', '@app.google_api', '@app.company_email_maker', '@app.google_users', '@app.google_groups', '@app.google_drive']
    tags:
        - { name: kernel.event_subscriber }

  app.receipt_subscriber:
    class: AppBundle\EventSubscriber\ReceiptSubscriber
    arguments: ['@app.logger', '@app.email_sender', '@session', '@security.token_storage']
    tags:
        - { name: kernel.event_subscriber }

  app.image_gallery_subscriber:
    class: AppBundle\EventSubscriber\ImageGallerySubscriber
    arguments: ['@app.logger', '@session']
    tags:
        - { name: kernel.event_subscriber }

  app.image_subscriber:
    class: AppBundle\EventSubscriber\ImageSubscriber
    arguments: ['@app.file_uploader']
    tags:
        - { name: doctrine.event_subscriber }

  app.db_subscriber:
    class: AppBundle\EventSubscriber\DbSubscriber
    arguments: ['@app.logger', '@doctrine.orm.default_entity_manager', '%kernel.environment%']
    tags:
      - { name: doctrine.event_subscriber }

  app.file_uploader:
      class: AppBundle\Service\FileUploader
      arguments: ['%signature_images%', '%logo_images%', '%receipt_images%', '%gallery_images%', '%profile_photos%', '%article_images%', '%logo_images%']

  security.login:
    class: AppBundle\Service\LoginManager
    arguments: ['@twig', '@security.authentication_utils', '@router']

  application.data:
    class: AppBundle\Service\ApplicationData
    arguments: ['@doctrine.orm.entity_manager', '@security.token_storage']

  app.application_admission:
    class: AppBundle\Service\ApplicationAdmission
    arguments: ['@doctrine.orm.default_entity_manager', '@twig', '@security.login']

  assistant_history.data:
      class: AppBundle\Service\AssistantHistoryData
      arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage', '@app.geolocation']

  survey.manager:
        class: AppBundle\Service\SurveyManager
        arguments: ['@doctrine.orm.default_entity_manager', '@form.factory']

  app.group_sorter_extension:
    class: AppBundle\Twig\Extension\TeamPositionSortExtension
    public: false
    arguments: ['@app.sorter', '@app.filter_service']
    tags:
      - { name: twig.extension }

  app.twig.extension.assets:
        class: AppBundle\Twig\Extension\AssetExtension
        arguments: ['@assets.packages', '%kernel.project_dir%']
        public: false
        tags:
          - { name: twig.extension }

  app.unique_company_email_validator:
    class: AppBundle\Validator\Constraints\UniqueCompanyEmailValidator
    arguments: ['@doctrine.orm.entity_manager', '@app.google_api']
    tags:
        - { name: validator.constraint_validator }

  app.application_email_validator:
    class: AppBundle\Validator\Constraints\ApplicationEmailValidator
    arguments: ['@app.application_admission']
    tags:
        - { name: validator.constraint_validator }

  app.info_meeting_validator:
    class: AppBundle\Validator\Constraints\InfoMeetingValidator
    tags:
        - { name: validator.constraint_validator }
