services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

#  app.form.type.article:
#   class: AppBundle\Form\Type\ArticleType
#    arguments:
#            - { name: form.type, alias: article }
  app.user.registration:
    class: AppBundle\UserRegistration\UserRegistration
    arguments: ['@twig']
  app.safe_html_extension:
    class: AppBundle\Twig\Extension\SafeHtmlExtension
    public: false
    tags:
      - { name: twig.extension }
