<?php

namespace App\Entity\Repository;

use App\Entity\Signature;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * SignatureRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignatureRepository extends EntityRepository
{
    /**
     * @param User $user
     *
     * @return Signature
     */
    public function findByUser(User $user)
    {
        return $this->createQueryBuilder('signature')
            ->select('signature')
            ->where('signature.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
