<?php

namespace App\Entity\Repository;

use App\Entity\StaticContent;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * StaticContentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticContentRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, StaticContent::class);
    }

    /**
     * @param string $htmlId
     *
     * @return StaticContent
     */
    public function findOneByHtmlId(string $htmlId)
    {
        return $this->createQueryBuilder('sc')
            ->where('sc.htmlId = :htmlId')
            ->setParameter('htmlId', $htmlId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
