<?php

namespace App\Entity\Repository;

use App\Entity\Team;
use App\Entity\TeamApplication;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * TeamApplicationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamApplicationRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, TeamApplication::class);
    }

    /**
     * @param Team $team
     *
     * @return TeamApplication[]
     */
    public function findByTeam(Team $team)
    {
        return $this->createQueryBuilder('teamApplication')
            ->select('teamApplication')
            ->where('teamApplication.team = :team')
            ->setParameter('team', $team)
            ->getQuery()
            ->getResult();
    }
}
