<?php

namespace App\Entity\Repository;

use App\Entity\UnhandledAccessRule;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * UnhandAccessRuleRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UnhandledAccessRuleRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, UnhandledAccessRule::class);
    }

    public function findByResourceAndMethod(string $resource, string $method)
    {
        return $this->createQueryBuilder('rule')
            ->where('rule.resource = :resource')
            ->setParameter('resource', $resource)
            ->andWhere('rule.method = :method')
            ->setParameter('method', $method)
            ->getQuery()
            ->getResult();
    }
}
