name: php cs fixer
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-22.04
    steps:
     - name: "Checkout code"
       uses: actions/checkout@v3

     - name: PHP-CS-Fixer
       uses: docker://oskarstark/php-cs-fixer-ga
       with:
         args: --diff --dry-run

  php unit:
    name: PHP-unit
    runs-on:
    steps:
      - name: Run unit and functional tests
        run: |
            php bin/phpunit --configuration phpunit.xml.dist --stop-on-failure

